version: "3" 
services:
  # WEB SERVER
  nginx:
    image: nginx:1.13
    volumes:
      - "./app:/var/www/html"
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
    ports:
      - "80:80"
    links:
      - web 

  # APLICAÇÃO
  web:
    #image: php:7.3-fpm
    build:
      .
    volumes:
      - "./app:/var/www/html"
    ports:
      - "9000:9000"
    links:
      - mysql
  
  # BANCO DE DADOS
  mysql:
    image: mysql:5.6
    ports:
      - "3306:3306"
    environment:
       MYSQL_ROOT_PASSWORD: 1234567
       MYSQL_DATABASE: teste
       MYSQL_USER: teste
       MYSQL_PASSWORD: 12324567
