  version: '3'
  
  services:
     web:
      image: php:7.3-fpm
      links:
        - db
      ports:
        - 80:80
        
    db:
      image: mysql:5.6
      ports:
          - 3306:3306
      environment:
          MYSQL_ROOT_PASSWORD: 123
          MYSQL_DATABASE: teste
          MYSQL_USER: teste
          MYSQL_PASSWORD: 123
 
